var name = "*Assignment Swap Two variables*";
console.log(name);
var sweety = "Sweety";
var cutie = "Cutie";
console.log("--------Before swap--------");
console.log(sweety, cutie);
var temp = "Sweety";
sweety = cutie;
cutie = temp;
console.log("--------After swap--------");
console.log(sweety, cutie);
var line = "==========================";
console.log(line);
var name = "*Assignment Swap Three values*";
console.log(name);
var num1 = "100";
var num2 = "200";
var num3 = "300";
console.log("--------Before swap--------");
console.log(num1, num2, num3);
var temp = "100";
num1 = num2;
num2 = num3;
num3 = temp;
console.log("--------After swap--------");
console.log(num1, num2, num3);
